package com.cesar31.system.view;

import com.cesar31.system.control.*;
import com.cesar31.system.model.Student;
import com.cesar31.system.model.User;
import com.cesar31.system.model.UserType;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar31
 */
public class CollaboratorView extends javax.swing.JFrame {

    private MainController control;
    private User user;
    private Crud crud;

    public CollaboratorView(User user, MainController control, Crud crud) {
        initComponents();
        this.control = control;
        this.user = user;
        this.crud = crud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        studentPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        userPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idUTxt = new javax.swing.JTextField();
        searchUButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editUButton = new javax.swing.JButton();
        delUButton = new javax.swing.JButton();
        addUButton = new javax.swing.JButton();
        passUText = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        typeUCombo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 163, 164));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 770));

        jTabbedPane1.setBackground(new java.awt.Color(153, 163, 164));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        studentPane.setBackground(new java.awt.Color(153, 163, 164));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estudiantes");

        idText.setBackground(new java.awt.Color(112, 123, 124));
        idText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        idText.setForeground(new java.awt.Color(0, 0, 0));

        searchButton.setBackground(new java.awt.Color(52, 152, 219));
        searchButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        searchButton.setForeground(new java.awt.Color(66, 73, 73));
        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        nameText.setBackground(new java.awt.Color(112, 123, 124));
        nameText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Direccion");

        addressText.setBackground(new java.awt.Color(112, 123, 124));
        addressText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addressText.setForeground(new java.awt.Color(0, 0, 0));

        editButton.setBackground(new java.awt.Color(52, 152, 219));
        editButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        editButton.setForeground(new java.awt.Color(66, 73, 73));
        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(52, 152, 219));
        delButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        delButton.setForeground(new java.awt.Color(66, 73, 73));
        delButton.setText("Eliminar");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(52, 152, 219));
        addButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(66, 73, 73));
        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPaneLayout = new javax.swing.GroupLayout(studentPane);
        studentPane.setLayout(studentPaneLayout);
        studentPaneLayout.setHorizontalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(nameText)
                    .addComponent(addressText)
                    .addGroup(studentPaneLayout.createSequentialGroup()
                        .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(255, 255, 255))
            .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPaneLayout.createSequentialGroup()
                    .addContainerGap(281, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(270, 270, 270)))
        );
        studentPaneLayout.setVerticalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(delButton))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(studentPaneLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel3)
                    .addContainerGap(632, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Estudiantes", studentPane);

        userPane.setBackground(new java.awt.Color(153, 163, 164));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Id");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usuarios");

        idUTxt.setBackground(new java.awt.Color(112, 123, 124));
        idUTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        idUTxt.setForeground(new java.awt.Color(0, 0, 0));

        searchUButton.setBackground(new java.awt.Color(52, 152, 219));
        searchUButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        searchUButton.setForeground(new java.awt.Color(66, 73, 73));
        searchUButton.setText("Buscar");
        searchUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario");

        userTxt.setBackground(new java.awt.Color(112, 123, 124));
        userTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        userTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password");

        editUButton.setBackground(new java.awt.Color(52, 152, 219));
        editUButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        editUButton.setForeground(new java.awt.Color(66, 73, 73));
        editUButton.setText("Editar");
        editUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUButtonActionPerformed(evt);
            }
        });

        delUButton.setBackground(new java.awt.Color(52, 152, 219));
        delUButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        delUButton.setForeground(new java.awt.Color(66, 73, 73));
        delUButton.setText("Eliminar");
        delUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUButtonActionPerformed(evt);
            }
        });

        addUButton.setBackground(new java.awt.Color(52, 152, 219));
        addUButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addUButton.setForeground(new java.awt.Color(66, 73, 73));
        addUButton.setText("Agregar");
        addUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUButtonActionPerformed(evt);
            }
        });

        passUText.setBackground(new java.awt.Color(112, 123, 124));
        passUText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        passUText.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo");

        typeUCombo.setBackground(new java.awt.Color(153, 163, 164));
        typeUCombo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        typeUCombo.setForeground(new java.awt.Color(0, 0, 0));
        typeUCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Colaborador" }));

        javax.swing.GroupLayout userPaneLayout = new javax.swing.GroupLayout(userPane);
        userPane.setLayout(userPaneLayout);
        userPaneLayout.setHorizontalGroup(
            userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPaneLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userPaneLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idUTxt)
                    .addComponent(userTxt)
                    .addGroup(userPaneLayout.createSequentialGroup()
                        .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchUButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editUButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(delUButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(passUText)
                    .addComponent(typeUCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(255, 255, 255))
        );
        userPaneLayout.setVerticalGroup(
            userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addGap(61, 61, 61)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idUTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passUText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(typeUCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchUButton)
                    .addComponent(addUButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUButton)
                    .addComponent(delUButton))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", userPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 163, 164));
        jMenuBar1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(153, 163, 164));
        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.control.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String id = idText.getText();
        if (!id.trim().isEmpty()) {
            Student s = control.getEdd().getStudents().get(id);
            if (s != null) {
                idText.setText(s.getId());
                nameText.setText(s.getName());
                addressText.setText(s.getAddress());
            } else {
                showMessage("El estudiante " + id + ", no existe.", "Informacion");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String id = idText.getText();
        String name = nameText.getText();
        String address = addressText.getText();

        crud.editStudent(id, name, address);


    }//GEN-LAST:event_editButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        String id = idText.getText();
        crud.deleteStudent(id);
    }//GEN-LAST:event_delButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String id = idText.getText();
        String name = nameText.getText();
        String address = addressText.getText();

        crud.addStudent(id, name, address);
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUButtonActionPerformed
        // TODO add your handling code here:
        String id = idUTxt.getText();
        if (!id.trim().isEmpty()) {
            control.getEdd().getUsers().getNode(id);
            if (control.getEdd().getUsers().getNode(id) != null) {
                User u = control.getEdd().getUsers().getNode(id).getData();
                if (!u.getType().equals(UserType.SUPER)) {
                    userTxt.setText(u.getUsername());
                    passUText.setText(u.getPassword());
                    // int index = u.getType().equals(UserType.STUDENT) ? 0 : 1;
                    typeUCombo.setSelectedIndex(u.getType().equals(UserType.STUDENT) ? 0 : 1);
                } else {
                    showMessage("El usuario " + id + ", no existe.", "Informacion");
                }
            } else {
                showMessage("El usuario " + id + ", no existe.", "Informacion");
            }
        }
    }//GEN-LAST:event_searchUButtonActionPerformed

    private void editUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUButtonActionPerformed

    private void delUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delUButtonActionPerformed

    private void addUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUButtonActionPerformed

    public void clearStudent() {
        idText.setText("");
        nameText.setText("");
        addressText.setText("");
    }

    public void showMessage(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    public User getUser() {
        return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addUButton;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton delButton;
    private javax.swing.JButton delUButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editUButton;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idUTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passUText;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchUButton;
    private javax.swing.JPanel studentPane;
    private javax.swing.JComboBox<String> typeUCombo;
    private javax.swing.JPanel userPane;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
