
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.system.parser;

/** CUP generated class containing symbol constants. */
public class CourseParserSym {
  /* terminals */
  public static final int INPUT = 17;
  public static final int COURSE = 9;
  public static final int RPAREN = 14;
  public static final int SEMI = 15;
  public static final int PROFESSOR = 8;
  public static final int ERROR = 21;
  public static final int USER = 3;
  public static final int STUDENT = 2;
  public static final int LPAREN = 13;
  public static final int COLLABORATOR = 4;
  public static final int INTERVAL = 19;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int BUILDING = 6;
  public static final int error = 1;
  public static final int STR = 20;
  public static final int STUDENT_ = 5;
  public static final int ASSIGNMENT = 11;
  public static final int INTEGER = 12;
  public static final int DAY = 18;
  public static final int SCHEDULE = 10;
  public static final int CLASSROOM = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STUDENT",
  "USER",
  "COLLABORATOR",
  "STUDENT_",
  "BUILDING",
  "CLASSROOM",
  "PROFESSOR",
  "COURSE",
  "SCHEDULE",
  "ASSIGNMENT",
  "INTEGER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COMMA",
  "INPUT",
  "DAY",
  "INTERVAL",
  "STR",
  "ERROR"
  };
}

