// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: course.flex

package com.cesar31.system.parser;

import static com.cesar31.system.parser.CourseParserSym.*;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class CourseLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\5\0\1\5\1\6\2\0\1\7\1\10"+
    "\2\0\1\11\11\12\1\13\1\14\5\0\1\15\1\16"+
    "\1\17\1\16\1\20\2\16\1\21\12\16\1\22\1\16"+
    "\1\23\5\16\1\0\1\24\2\0\1\16\1\0\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\16\1\34"+
    "\2\16\1\35\1\36\1\37\1\40\1\41\1\16\1\42"+
    "\1\43\1\44\1\45\5\16\57\0\1\16\12\0\1\16"+
    "\4\0\1\16\5\0\27\16\1\0\37\16\1\0\u01ca\16"+
    "\4\0\14\16\16\0\5\16\7\0\1\16\1\0\1\16"+
    "\21\0\165\16\1\0\2\16\2\0\4\16\1\0\1\16"+
    "\6\0\1\16\1\0\3\16\1\0\1\16\1\0\24\16"+
    "\1\0\123\16\1\0\213\16\1\0\255\16\1\0\46\16"+
    "\2\0\1\16\6\0\51\16\10\0\55\16\1\0\1\16"+
    "\1\0\2\16\1\0\2\16\1\0\1\16\10\0\33\16"+
    "\4\0\4\16\35\0\13\16\5\0\100\16\12\46\4\0"+
    "\146\16\1\0\10\16\2\0\12\16\1\0\6\16\12\46"+
    "\3\16\2\0\1\16\20\0\73\16\2\0\145\16\16\0"+
    "\12\46\54\16\4\0\1\16\2\0\1\16\2\0\56\16"+
    "\22\0\34\16\4\0\13\16\65\0\25\16\1\0\10\16"+
    "\25\0\17\16\1\0\201\16\2\0\12\46\1\0\23\16"+
    "\1\0\10\16\2\0\2\16\2\0\26\16\1\0\7\16"+
    "\1\0\1\16\3\0\4\16\2\0\11\16\2\0\2\16"+
    "\2\0\4\16\10\0\1\16\4\0\2\16\1\0\5\16"+
    "\2\0\12\46\2\16\12\0\1\16\1\0\1\16\2\0"+
    "\3\16\1\0\6\16\4\0\2\16\2\0\26\16\1\0"+
    "\7\16\1\0\2\16\1\0\2\16\1\0\2\16\2\0"+
    "\1\16\1\0\5\16\4\0\2\16\2\0\3\16\3\0"+
    "\1\16\7\0\4\16\1\0\1\16\7\0\12\46\6\16"+
    "\13\0\3\16\1\0\11\16\1\0\3\16\1\0\26\16"+
    "\1\0\7\16\1\0\2\16\1\0\5\16\2\0\12\16"+
    "\1\0\3\16\1\0\3\16\2\0\1\16\17\0\4\16"+
    "\2\0\12\46\11\0\7\16\1\0\3\16\1\0\10\16"+
    "\2\0\2\16\2\0\26\16\1\0\7\16\1\0\2\16"+
    "\1\0\5\16\2\0\11\16\2\0\2\16\2\0\3\16"+
    "\10\0\2\16\4\0\2\16\1\0\5\16\2\0\12\46"+
    "\1\0\1\16\20\0\2\16\1\0\6\16\3\0\3\16"+
    "\1\0\4\16\3\0\2\16\1\0\1\16\1\0\2\16"+
    "\3\0\2\16\3\0\3\16\3\0\14\16\4\0\5\16"+
    "\3\0\3\16\1\0\4\16\2\0\1\16\6\0\1\16"+
    "\16\0\12\46\20\0\15\16\1\0\3\16\1\0\27\16"+
    "\1\0\20\16\3\0\10\16\1\0\3\16\1\0\4\16"+
    "\7\0\2\16\1\0\3\16\5\0\4\16\2\0\12\46"+
    "\20\0\4\16\1\0\10\16\1\0\3\16\1\0\27\16"+
    "\1\0\12\16\1\0\5\16\2\0\11\16\1\0\3\16"+
    "\1\0\4\16\7\0\2\16\7\0\1\16\1\0\4\16"+
    "\2\0\12\46\1\0\2\16\15\0\4\16\1\0\10\16"+
    "\1\0\3\16\1\0\63\16\1\0\3\16\1\0\5\16"+
    "\5\0\4\16\7\0\5\16\2\0\12\46\12\0\6\16"+
    "\2\0\2\16\1\0\22\16\3\0\30\16\1\0\11\16"+
    "\1\0\1\16\2\0\7\16\3\0\1\16\4\0\6\16"+
    "\1\0\1\16\1\0\10\16\6\0\12\46\2\0\2\16"+
    "\15\0\72\16\5\0\17\16\1\0\12\46\47\0\2\16"+
    "\1\0\1\16\1\0\5\16\1\0\30\16\1\0\1\16"+
    "\1\0\27\16\2\0\5\16\1\0\1\16\1\0\6\16"+
    "\2\0\12\46\2\0\4\16\40\0\1\16\27\0\2\16"+
    "\6\0\12\46\13\0\1\16\1\0\1\16\1\0\1\16"+
    "\4\0\12\16\1\0\44\16\4\0\24\16\1\0\22\16"+
    "\1\0\44\16\11\0\1\16\71\0\100\16\12\46\6\0"+
    "\100\16\12\46\4\16\2\0\46\16\1\0\1\16\5\0"+
    "\1\16\2\0\53\16\1\0\115\16\1\0\4\16\2\0"+
    "\7\16\1\0\1\16\1\0\4\16\2\0\51\16\1\0"+
    "\4\16\2\0\41\16\1\0\4\16\2\0\7\16\1\0"+
    "\1\16\1\0\4\16\2\0\17\16\1\0\71\16\1\0"+
    "\4\16\2\0\103\16\2\0\3\16\40\0\20\16\20\0"+
    "\126\16\2\0\6\16\3\0\u016c\16\2\0\21\16\1\0"+
    "\32\16\5\0\113\16\3\0\13\16\7\0\15\16\1\0"+
    "\7\16\13\0\25\16\13\0\24\16\14\0\15\16\1\0"+
    "\3\16\1\0\2\16\14\0\124\16\3\0\1\16\4\0"+
    "\2\16\2\0\12\46\41\0\3\16\2\0\12\46\6\0"+
    "\131\16\7\0\53\16\5\0\106\16\12\0\37\16\1\0"+
    "\14\16\4\0\14\16\12\0\12\46\36\16\2\0\5\16"+
    "\13\0\54\16\4\0\32\16\6\0\12\46\46\0\34\16"+
    "\4\0\77\16\1\0\35\16\2\0\1\16\12\46\6\0"+
    "\12\46\15\0\1\16\10\0\17\16\101\0\114\16\4\0"+
    "\12\46\21\0\11\16\14\0\60\16\12\46\72\16\14\0"+
    "\70\16\10\0\12\46\3\0\3\16\12\46\44\16\2\0"+
    "\11\16\7\0\53\16\2\0\3\16\20\0\3\16\1\0"+
    "\47\16\5\0\372\16\1\0\33\16\2\0\6\16\2\0"+
    "\46\16\2\0\6\16\2\0\10\16\1\0\1\16\1\0"+
    "\1\16\1\0\1\16\1\0\37\16\2\0\65\16\1\0"+
    "\7\16\1\0\1\16\3\0\3\16\1\0\7\16\3\0"+
    "\4\16\2\0\6\16\4\0\15\16\5\0\3\16\1\0"+
    "\7\16\102\0\2\16\23\0\1\16\34\0\1\16\15\0"+
    "\1\16\20\0\15\16\63\0\41\16\21\0\1\16\4\0"+
    "\1\16\2\0\12\16\1\0\1\16\3\0\5\16\6\0"+
    "\1\16\1\0\1\16\1\0\1\16\1\0\4\16\1\0"+
    "\13\16\2\0\4\16\5\0\5\16\4\0\1\16\21\0"+
    "\51\16\u022d\0\64\16\26\0\57\16\1\0\57\16\1\0"+
    "\205\16\6\0\11\16\14\0\46\16\1\0\1\16\5\0"+
    "\1\16\2\0\70\16\7\0\1\16\17\0\30\16\11\0"+
    "\7\16\1\0\7\16\1\0\7\16\1\0\7\16\1\0"+
    "\7\16\1\0\7\16\1\0\7\16\1\0\7\16\1\0"+
    "\40\16\57\0\1\16\325\0\3\16\31\0\17\16\1\0"+
    "\5\16\2\0\5\16\4\0\126\16\2\0\2\16\2\0"+
    "\3\16\1\0\132\16\1\0\4\16\5\0\53\16\1\0"+
    "\136\16\21\0\33\16\65\0\306\16\112\0\360\16\20\0"+
    "\215\16\103\0\56\16\2\0\15\16\3\0\20\16\12\46"+
    "\2\16\24\0\63\16\1\0\12\16\1\0\163\16\45\0"+
    "\11\16\2\0\147\16\2\0\65\16\2\0\5\16\60\0"+
    "\61\16\30\0\64\16\14\0\106\16\12\0\12\46\6\0"+
    "\30\16\3\0\1\16\1\0\3\16\12\46\44\16\2\0"+
    "\44\16\14\0\35\16\3\0\101\16\16\0\1\16\12\46"+
    "\6\0\20\16\12\46\5\16\1\0\67\16\11\0\16\16"+
    "\2\0\12\46\6\0\27\16\3\0\111\16\30\0\3\16"+
    "\2\0\20\16\2\0\5\16\12\0\6\16\2\0\6\16"+
    "\2\0\6\16\11\0\7\16\1\0\7\16\1\0\53\16"+
    "\1\0\14\16\10\0\173\16\1\0\2\16\2\0\12\46"+
    "\6\0\244\16\14\0\27\16\4\0\61\16\4\0\156\16"+
    "\2\0\152\16\46\0\7\16\14\0\5\16\5\0\14\16"+
    "\1\0\15\16\1\0\5\16\1\0\1\16\1\0\2\16"+
    "\1\0\2\16\1\0\154\16\41\0\153\16\22\0\100\16"+
    "\2\0\66\16\50\0\14\16\4\0\20\16\20\0\20\16"+
    "\3\0\2\16\30\0\3\16\40\0\5\16\1\0\207\16"+
    "\23\0\12\46\7\0\32\16\4\0\1\16\1\0\32\16"+
    "\13\0\131\16\3\0\6\16\2\0\6\16\2\0\6\16"+
    "\2\0\3\16\43\0\14\16\1\0\32\16\1\0\23\16"+
    "\1\0\2\16\1\0\17\16\2\0\16\16\42\0\173\16"+
    "\105\0\65\16\210\0\1\16\202\0\35\16\3\0\61\16"+
    "\17\0\1\16\37\0\40\16\15\0\36\16\5\0\53\16"+
    "\5\0\36\16\2\0\44\16\4\0\10\16\1\0\5\16"+
    "\52\0\236\16\2\0\12\46\6\0\44\16\4\0\44\16"+
    "\4\0\50\16\10\0\64\16\234\0\67\16\11\0\26\16"+
    "\12\0\10\16\230\0\6\16\2\0\1\16\1\0\54\16"+
    "\1\0\2\16\3\0\1\16\2\0\27\16\12\0\27\16"+
    "\11\0\37\16\101\0\23\16\1\0\2\16\12\0\26\16"+
    "\12\0\32\16\106\0\70\16\6\0\2\16\100\0\4\16"+
    "\1\0\2\16\5\0\10\16\1\0\3\16\1\0\35\16"+
    "\2\0\3\16\4\0\1\16\40\0\35\16\3\0\35\16"+
    "\43\0\10\16\1\0\36\16\31\0\66\16\12\0\26\16"+
    "\12\0\23\16\15\0\22\16\156\0\111\16\67\0\63\16"+
    "\15\0\63\16\15\0\50\16\10\0\12\46\306\0\35\16"+
    "\12\0\1\16\10\0\41\16\217\0\27\16\11\0\107\16"+
    "\37\0\12\46\17\0\74\16\25\0\31\16\7\0\12\46"+
    "\6\0\65\16\1\0\12\46\4\0\3\16\11\0\44\16"+
    "\2\0\1\16\11\0\105\16\4\0\4\16\3\0\12\46"+
    "\1\16\1\0\1\16\43\0\22\16\1\0\45\16\6\0"+
    "\1\16\101\0\7\16\1\0\1\16\1\0\4\16\1\0"+
    "\17\16\1\0\12\16\7\0\73\16\5\0\12\46\6\0"+
    "\4\16\1\0\10\16\2\0\2\16\2\0\26\16\1\0"+
    "\7\16\1\0\2\16\1\0\5\16\1\0\12\16\2\0"+
    "\2\16\2\0\3\16\2\0\1\16\6\0\1\16\5\0"+
    "\7\16\2\0\7\16\3\0\5\16\213\0\113\16\5\0"+
    "\12\46\4\0\2\16\40\0\106\16\1\0\1\16\10\0"+
    "\12\46\246\0\66\16\2\0\11\16\27\0\6\16\42\0"+
    "\101\16\3\0\1\16\13\0\12\46\46\0\71\16\7\0"+
    "\12\46\66\0\33\16\2\0\17\16\4\0\12\46\306\0"+
    "\73\16\145\0\100\16\12\46\25\0\1\16\240\0\10\16"+
    "\2\0\56\16\2\0\10\16\1\0\2\16\33\0\77\16"+
    "\10\0\1\16\10\0\112\16\3\0\1\16\42\0\71\16"+
    "\7\0\11\16\1\0\55\16\1\0\11\16\17\0\12\46"+
    "\30\0\36\16\2\0\26\16\1\0\16\16\111\0\7\16"+
    "\1\0\2\16\1\0\54\16\3\0\1\16\1\0\2\16"+
    "\1\0\11\16\10\0\12\46\6\0\6\16\1\0\2\16"+
    "\1\0\45\16\1\0\2\16\1\0\6\16\7\0\12\46"+
    "\u0136\0\27\16\11\0\232\16\146\0\157\16\21\0\304\16"+
    "\274\0\57\16\321\0\107\16\271\0\71\16\7\0\37\16"+
    "\1\0\12\46\146\0\36\16\2\0\5\16\13\0\67\16"+
    "\11\0\4\16\14\0\12\46\11\0\25\16\5\0\23\16"+
    "\260\0\100\16\200\0\113\16\4\0\71\16\7\0\21\16"+
    "\100\0\2\16\1\0\1\16\34\0\370\16\10\0\363\16"+
    "\15\0\37\16\61\0\3\16\21\0\4\16\10\0\u018c\16"+
    "\4\0\153\16\5\0\15\16\3\0\11\16\7\0\12\16"+
    "\3\0\2\16\306\0\5\16\3\0\6\16\10\0\10\16"+
    "\2\0\7\16\36\0\4\16\224\0\3\16\273\0\125\16"+
    "\1\0\107\16\1\0\2\16\2\0\1\16\2\0\2\16"+
    "\2\0\4\16\1\0\14\16\1\0\1\16\1\0\7\16"+
    "\1\0\101\16\1\0\4\16\2\0\10\16\1\0\7\16"+
    "\1\0\34\16\1\0\4\16\1\0\5\16\1\0\1\16"+
    "\3\0\7\16\1\0\u0154\16\2\0\31\16\1\0\31\16"+
    "\1\0\37\16\1\0\31\16\1\0\37\16\1\0\31\16"+
    "\1\0\37\16\1\0\31\16\1\0\37\16\1\0\31\16"+
    "\1\0\10\16\2\0\62\46\67\16\4\0\62\16\10\0"+
    "\1\16\16\0\1\16\26\0\5\16\1\0\17\16\120\0"+
    "\7\16\1\0\21\16\2\0\7\16\1\0\2\16\1\0"+
    "\5\16\325\0\55\16\3\0\16\16\2\0\12\46\4\0"+
    "\1\16\u0171\0\60\16\12\46\6\0\305\16\13\0\7\16"+
    "\51\0\114\16\4\0\12\46\246\0\4\16\1\0\33\16"+
    "\1\0\2\16\1\0\1\16\2\0\1\16\1\0\12\16"+
    "\1\0\4\16\1\0\1\16\1\0\1\16\6\0\1\16"+
    "\4\0\1\16\1\0\1\16\1\0\1\16\1\0\3\16"+
    "\1\0\2\16\1\0\1\16\2\0\1\16\1\0\1\16"+
    "\1\0\1\16\1\0\1\16\1\0\1\16\1\0\2\16"+
    "\1\0\1\16\2\0\4\16\1\0\7\16\1\0\4\16"+
    "\1\0\4\16\1\0\1\16\1\0\12\16\1\0\21\16"+
    "\5\0\3\16\1\0\5\16\1\0\21\16\164\0\32\16"+
    "\6\0\32\16\6\0\32\16\166\0\327\16\51\0\65\16"+
    "\13\0\336\16\2\0\u0182\16\16\0\u0131\16\37\0\36\16"+
    "\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29440];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\2\7"+
    "\1\10\11\11\1\12\1\13\1\12\1\14\12\11\2\12"+
    "\1\15\1\16\1\17\1\20\12\11\1\12\12\11\1\12"+
    "\2\11\1\21\3\11\1\22\3\11\1\12\10\11\1\12"+
    "\1\23\3\11\1\24\1\25\2\11\1\12\1\11\1\26"+
    "\3\11\1\12\4\11\2\12\1\11\1\27\1\11\1\30"+
    "\1\12\1\31\1\32\2\12\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\116\0\165\0\116\0\116\0\116"+
    "\0\116\0\234\0\303\0\116\0\352\0\234\0\u0111\0\u0138"+
    "\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\116\0\u0249"+
    "\0\u0270\0\u0297\0\u02be\0\u02e5\0\u030c\0\u0333\0\u035a\0\u0381"+
    "\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\116\0\116\0\116"+
    "\0\116\0\u046b\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555"+
    "\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666\0\u068d"+
    "\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\u079e\0\u07c5"+
    "\0\u07ec\0\234\0\u0813\0\u083a\0\u0861\0\234\0\u0888\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\u0972\0\u0999\0\u09c0\0\u09e7"+
    "\0\u0a0e\0\u0a35\0\u0a5c\0\234\0\u0a83\0\u0aaa\0\u0ad1\0\234"+
    "\0\234\0\u0af8\0\u0b1f\0\u0b46\0\u0b6d\0\234\0\u0b94\0\u0bbb"+
    "\0\u0be2\0\u0c09\0\u0c30\0\u0c57\0\u0c7e\0\u0ca5\0\u0ccc\0\u0cf3"+
    "\0\u0d1a\0\234\0\u0d41\0\234\0\u0d68\0\234\0\234\0\u0d8f"+
    "\0\u0db6\0\u0222";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\3\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\3\2\16\1\24\1\16\1\25"+
    "\15\16\2\26\2\3\1\27\4\26\2\30\11\26\1\31"+
    "\21\26\1\30\51\0\1\4\55\0\2\16\2\0\7\16"+
    "\1\0\22\16\11\0\2\13\2\0\7\16\1\0\22\16"+
    "\11\0\2\16\2\0\7\16\1\0\16\16\1\32\3\16"+
    "\11\0\2\16\2\0\7\16\1\0\1\33\17\16\1\34"+
    "\1\16\11\0\2\16\2\0\7\16\1\0\3\16\1\35"+
    "\12\16\1\36\3\16\11\0\2\16\2\0\7\16\1\0"+
    "\13\16\1\37\6\16\11\0\2\16\2\0\7\16\1\0"+
    "\1\40\21\16\11\0\2\16\2\0\7\16\1\0\16\16"+
    "\1\41\3\16\11\0\2\16\2\0\7\16\1\0\13\16"+
    "\1\42\6\16\11\0\2\16\2\0\7\16\1\0\16\16"+
    "\1\43\3\16\2\26\3\0\17\26\1\0\24\26\3\0"+
    "\4\26\2\44\1\45\10\26\1\0\21\26\1\44\4\0"+
    "\1\46\32\0\1\47\2\0\1\50\1\0\1\51\13\0"+
    "\2\16\2\0\7\16\1\0\7\16\1\52\12\16\11\0"+
    "\2\16\2\0\7\16\1\0\17\16\1\53\2\16\11\0"+
    "\2\16\2\0\7\16\1\0\15\16\1\54\4\16\11\0"+
    "\2\16\2\0\7\16\1\0\7\16\1\55\12\16\11\0"+
    "\2\16\2\0\7\16\1\0\17\16\1\56\2\16\11\0"+
    "\2\16\2\0\7\16\1\0\15\16\1\57\4\16\11\0"+
    "\2\16\2\0\7\16\1\0\10\16\1\60\11\16\11\0"+
    "\2\16\2\0\7\16\1\0\20\16\1\61\1\16\11\0"+
    "\2\16\2\0\7\16\1\0\10\16\1\62\11\16\11\0"+
    "\2\16\2\0\7\16\1\0\17\16\1\63\2\16\2\26"+
    "\3\0\6\26\1\45\10\26\1\0\24\26\3\0\4\26"+
    "\2\64\11\26\1\0\21\26\1\64\11\0\2\16\2\0"+
    "\7\16\1\0\6\16\1\65\13\16\11\0\2\16\2\0"+
    "\7\16\1\0\4\16\1\66\15\16\11\0\2\16\2\0"+
    "\7\16\1\0\16\16\1\67\3\16\11\0\2\16\2\0"+
    "\7\16\1\0\5\16\1\70\14\16\11\0\2\16\2\0"+
    "\7\16\1\0\20\16\1\71\1\16\11\0\2\16\2\0"+
    "\7\16\1\0\1\72\21\16\11\0\2\16\2\0\7\16"+
    "\1\0\13\16\1\73\6\16\11\0\2\16\2\0\7\16"+
    "\1\0\1\74\21\16\11\0\2\16\2\0\7\16\1\0"+
    "\1\75\21\16\11\0\2\16\2\0\7\16\1\0\20\16"+
    "\1\76\1\16\2\26\3\0\4\26\2\77\11\26\1\0"+
    "\21\26\1\77\11\0\2\16\2\0\7\16\1\0\12\16"+
    "\1\100\7\16\11\0\2\16\2\0\7\16\1\0\3\16"+
    "\1\101\16\16\11\0\2\16\2\0\7\16\1\0\13\16"+
    "\1\102\6\16\11\0\2\16\2\0\7\16\1\0\7\16"+
    "\1\103\12\16\11\0\2\16\2\0\7\16\1\0\3\16"+
    "\1\104\16\16\11\0\2\16\2\0\7\16\1\0\15\16"+
    "\1\105\4\16\11\0\2\16\2\0\7\16\1\0\12\16"+
    "\1\106\7\16\11\0\2\16\2\0\7\16\1\0\15\16"+
    "\1\107\4\16\11\0\2\16\2\0\7\16\1\0\1\16"+
    "\1\110\20\16\11\0\2\16\2\0\7\16\1\0\3\16"+
    "\1\111\16\16\2\26\3\0\17\26\1\0\1\112\13\26"+
    "\1\112\5\26\11\0\2\16\2\0\7\16\1\0\1\113"+
    "\21\16\11\0\2\16\2\0\7\16\1\0\15\16\1\114"+
    "\4\16\11\0\2\16\2\0\7\16\1\0\2\16\1\115"+
    "\17\16\11\0\2\16\2\0\7\16\1\0\7\16\1\116"+
    "\12\16\11\0\2\16\2\0\7\16\1\0\7\16\1\117"+
    "\12\16\11\0\2\16\2\0\7\16\1\0\7\16\1\120"+
    "\12\16\11\0\2\16\2\0\7\16\1\0\13\16\1\121"+
    "\6\16\11\0\2\16\2\0\7\16\1\0\7\16\1\122"+
    "\12\16\2\26\3\0\17\26\1\0\11\26\1\123\10\26"+
    "\11\0\2\16\2\0\7\16\1\0\15\16\1\124\4\16"+
    "\11\0\2\16\2\0\7\16\1\0\1\125\21\16\11\0"+
    "\2\16\2\0\7\16\1\0\7\16\1\126\12\16\11\0"+
    "\2\16\2\0\7\16\1\0\1\127\21\16\11\0\2\16"+
    "\2\0\7\16\1\0\13\16\1\130\6\16\11\0\2\16"+
    "\2\0\7\16\1\0\13\16\1\131\6\16\11\0\2\16"+
    "\2\0\7\16\1\0\15\16\1\132\4\16\11\0\2\16"+
    "\2\0\7\16\1\0\1\133\21\16\2\26\3\0\3\26"+
    "\1\134\13\26\1\0\22\26\11\0\2\16\2\0\7\16"+
    "\1\0\17\16\1\135\2\16\11\0\2\16\2\0\7\16"+
    "\1\0\13\16\1\136\6\16\11\0\2\16\2\0\7\16"+
    "\1\0\12\16\1\137\7\16\11\0\2\16\2\0\7\16"+
    "\1\0\1\140\21\16\11\0\2\16\2\0\7\16\1\0"+
    "\12\16\1\141\7\16\2\26\3\0\4\26\2\142\11\26"+
    "\1\0\21\26\1\142\11\0\2\16\2\0\7\16\1\0"+
    "\7\16\1\143\12\16\11\0\2\16\2\0\7\16\1\0"+
    "\17\16\1\144\2\16\11\0\2\16\2\0\7\16\1\0"+
    "\3\16\1\145\16\16\11\0\2\16\2\0\7\16\1\0"+
    "\17\16\1\146\2\16\2\26\3\0\4\26\2\147\1\150"+
    "\10\26\1\0\21\26\1\147\11\0\2\16\2\0\7\16"+
    "\1\0\2\16\1\151\17\16\11\0\2\16\2\0\7\16"+
    "\1\0\4\16\1\152\15\16\11\0\2\16\2\0\7\16"+
    "\1\0\13\16\1\153\6\16\11\0\2\16\2\0\7\16"+
    "\1\0\4\16\1\154\15\16\2\26\3\0\6\26\1\150"+
    "\10\26\1\0\24\26\3\0\4\26\2\155\11\26\1\0"+
    "\21\26\1\155\11\0\2\16\2\0\7\16\1\0\13\16"+
    "\1\156\6\16\11\0\2\16\2\0\7\16\1\0\15\16"+
    "\1\157\4\16\2\26\3\0\4\26\2\160\11\26\1\0"+
    "\21\26\1\160\2\26\3\0\17\26\1\0\1\161\13\26"+
    "\1\161\7\26\3\0\17\26\1\0\11\26\1\162\10\26";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3549];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\4\11\2\1\1\11\12\1\1\11"+
    "\16\1\4\11\111\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
		private StringBuffer string = new StringBuffer();
		private boolean isSc = false;
		private int len = 0;

		private Symbol setString(int type, String s) {
			if(isSc && s.length() == len) {
				isSc = false;
				len = 0;
				return symbol(INTERVAL, s);
			}

			switch (s) {
				case "lunes":
				case "martes":
				case "miercoles":
				case "jueves":
				case "viernes":
				case "sabado":
				case "domingo":
					return symbol(DAY, s);

				default:
					return symbol(type, s);
			}
		}

		private Symbol symbol(int type) {
			return new Symbol(type, yyline + 1, yycolumn + 1);
		}

		private Symbol symbol(int type, Object object) {
			return new Symbol(type, yyline + 1, yycolumn + 1, object);
		}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CourseLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error: < " + yytext() + " >");
	return symbol(ERROR, yytext());
            }
            // fall through
          case 28: break;
          case 2:
            { /* Ignore */
            }
            // fall through
          case 29: break;
          case 3:
            { string.setLength(0);
		yybegin(STRING);
            }
            // fall through
          case 30: break;
          case 4:
            { return symbol(LPAREN);
            }
            // fall through
          case 31: break;
          case 5:
            { return symbol(RPAREN);
            }
            // fall through
          case 32: break;
          case 6:
            { return symbol(COMMA);
            }
            // fall through
          case 33: break;
          case 7:
            { return symbol(INTEGER, yytext());
            }
            // fall through
          case 34: break;
          case 8:
            { return symbol(SEMI);
            }
            // fall through
          case 35: break;
          case 9:
            { return symbol(INPUT, yytext());
            }
            // fall through
          case 36: break;
          case 10:
            { string.append( yytext() );
            }
            // fall through
          case 37: break;
          case 11:
            { yybegin(YYINITIAL);
		return setString(STR, string.toString());
            }
            // fall through
          case 38: break;
          case 12:
            { string.append('\\');
            }
            // fall through
          case 39: break;
          case 13:
            { string.append('\"');
            }
            // fall through
          case 40: break;
          case 14:
            { string.append('\n');
            }
            // fall through
          case 41: break;
          case 15:
            { string.append('\r');
            }
            // fall through
          case 42: break;
          case 16:
            { string.append('\t');
            }
            // fall through
          case 43: break;
          case 17:
            { return symbol(COURSE);
            }
            // fall through
          case 44: break;
          case 18:
            { return symbol(CLASSROOM);
            }
            // fall through
          case 45: break;
          case 19:
            { return symbol(ASSIGNMENT);
            }
            // fall through
          case 46: break;
          case 20:
            { return symbol(SCHEDULE);
            }
            // fall through
          case 47: break;
          case 21:
            { return symbol(USER);
            }
            // fall through
          case 48: break;
          case 22:
            { return symbol(BUILDING);
            }
            // fall through
          case 49: break;
          case 23:
            { return symbol(STUDENT);
            }
            // fall through
          case 50: break;
          case 24:
            { return symbol(STUDENT_, yytext());
            }
            // fall through
          case 51: break;
          case 25:
            { return symbol(PROFESSOR);
            }
            // fall through
          case 52: break;
          case 26:
            { return symbol(COLLABORATOR, yytext());
            }
            // fall through
          case 53: break;
          case 27:
            { string.append(yytext());
		len = yytext().length();
		isSc = true;
            }
            // fall through
          case 54: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
